version: '3.6'
services:
  project-assessment:
    container_name: project-assessment
    image: project_assessment_image
    build: ./project-assessment-site
    ports:
      - "80:80"
  department-service:
    container_name: department-service
    image: department_image
    build: ./department-service
    ports:
      - "8083:80"
  person-service:
    container_name: person-service
    image: person_image
    build: ./person-service
    ports: 
      - "8081:80"
  role-service:
    container_name: role-service
    image: role_image
    build: ./role-service
    ports:
      - "8082:80"
  office-service:
    container_name: office-service
    image: office_image
    build: ./office-service
    ports:
      - "8084:80"   
