apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: office
spec:
  selector:
    matchLabels:
      app: office
  replicas: 1
  template:
    metadata:
      labels:
        app: office
    spec:
      containers:
      - name: office-service
        image: abdul125/office-service:latest
        ports:
        - containerPort: 80
