#https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

apiVersion: v1
kind: Deployment
metadata:
  name: office-deployment
spec:
  selector:
    matchLabels:
      app: office-api
  replicas: 2
  template:
    metadata:
      labels:
        app: office-api
    spec:
      containers:
      - name: office-service
        image: abdul125/office-service
        ports:
        - containerPort: 80
