#https://kubernetes.io/docs/concepts/services-networking/service/

apiVersion: v1
kind: Service
metadata:
  name: office-service
spec:
  selector:
    app: office
  ports:
    - port: 80
  selector:
    app: office-api
