# https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: department
spec:
  selector:
    matchLabels:
      app: department
  replicas: 1
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
      - name: department-service
        image: abdul125/department-service
        ports:
        - containerPort: 80 

