apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
  namespace: test
spec:
  selector:
    matchLabels:
      app: department
  replicas: 1
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
      - name: department-service
        image: abdul125/department-service
        ports:
        - containerPort: 80
