pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    service_name: project-assessment-site
    service_type: REST
spec:
  containers:
  - name: dnd
    image: docker:latest
    command: 
    - cat
    tty: true
    volumeMounts: 
    - mountPath: /var/run/docker.sock
      name: docker-sock
    - name: vsecret
      mountPath: /etc/vsecret
      readOnly: true
  - name: kubectl
    image: bryandollery/terraform-packer-aws-alpine
    command:
    - cat
    tty: true
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock  
      type: Socket
   volumes:
 - name: vsecret
   secret:
     secretName: mysecret
"""
    }
  }
  environment {
    DOCKER_NAMESPACE = 'abdul125'
    SERVICE_NAME = 'project-assessment-site'
    TOKEN=credentials('d6e8fbda-de90-4de8-a35f-67bb86281a8b')
  }
  stages {
      stage("Build") {
          steps {
              container('dnd') {
                  sh '''
                      cd $SERVICE_NAME
		      ls -aAlth /etc/
		   
                      docker build --tag $DOCKER_NAMESPACE/$SERVICE_NAME .
                  '''
              }
          }
      }
      stage("Release") {
          steps {
              container('dnd') {
		      sh '''
		      cat /etc/vsecret/docker-token 
                      docker login -u $DOCKER_NAMESPACE -p $CREDS_PSW
                      docker push $DOCKER_NAMESPACE/$SERVICE_NAME
                  '''
              }
          }
      }
      stage("Deploy") {
          steps {
              container('kubectl') {
                  sh '''
                      cd $SERVICE_NAME
                      kubectl --token=$TOKEN -n test apply -f deploy.yaml -f service.yaml -f ingress.yaml
                      kubectl --token=$TOKEN -n test get all
                  '''
              }
          }
      }
  }
}

